#!/bin/bash
#PBS -P ob80
#PBS -q normal
#PBS -l ncpus=1
#PBS -l mem=4GB
#PBS -l jobfs=6GB
#PBS -l walltime=60:00
#PBS -l wd
#PBS -l other=hyperthread
#PBS -l storage=scratch/ob80+gdata/ob80
#PBS -N fastp


set -euo pipefail
eval "$(conda shell.bash hook)"
conda activate bioinformatics

mkdir -p fastq_fastp

if [[ $R1 ]] && [[ $R2 ]]; then
	OUTR1=`basename $R1`
	OUTR2=`basename $R2`
	mkdir $PBS_JOBFS/fastp/
	fastp -n 1 -l 100 -i $R1 -I $R2  -o  $PBS_JOBFS/fastp/$OUTR1 -O $PBS_JOBFS/fastp/$OUTR2 --adapter_fasta ~/GitHubs/atavide_lite/adapters/IlluminaAdapters.fa
	mv -t fastq_fastp/ $PBS_JOBFS/fastp/$OUTR1  $PBS_JOBFS/fastp/$OUTR2
elif [[ $R1 ]]; then
	OUTR1=`basename $R1`
	mkdir $PBS_JOBFS/fastp/
	fastp -n 1 -l 100 -i $R1 -o  $PBS_JOBFS/fastp/$OUTR1 --adapter_fasta ~/GitHubs/atavide_lite/adapters/IlluminaAdapters.fa
	mv -t fastq_fastp/ $PBS_JOBFS/fastp/$OUTR1
elif [[ $R2 ]]; then
	OUTR2=`basename $R2`
	mkdir $PBS_JOBFS/fastp/
	fastp -n 1 -l 100 -i $R2 -o  $PBS_JOBFS/fastp/$OUTR2 --adapter_fasta ~/GitHubs/atavide_lite/adapters/IlluminaAdapters.fa
	mv -t fastq_fastp/ $PBS_JOBFS/fastp/$OUTR2
else
	echo "Please define the variables R1 and/or R2. e.g. qsub -v R1=R1.fastq,R2=R2.fasta" >&2
fi


